### ISSUE TITLE
Improve user interface for podcast player

### ISSUE THREAD

**Issue by davidebukali** [devinit/DIwebsite-redesign#1155]
**Is your feature request related to a problem? Please describe.**
The player is not intuitive and some users could miss the fact that it can be played
<img width="1186" alt="Screenshot 2022-06-16 at 17 36 06" src="https://user-images.githubusercontent.com/1607276/174094425-87e072db-6510-4048-82e5-0dd73753089c.png">

**Describe alternatives you've considered**
Improve the interface to something similar to Soundcloud.
<img width="645" alt="Screenshot 2022-06-16 at 17 42 58" src="https://user-images.githubusercontent.com/1607276/174096118-90a3da3c-bae2-4d85-bc81-828929351d74.png">

**Additional context**

**Requested Delivery Date:** dd/MMM/YYYY

**Comment by Tim-Molyneux** [comment]
Thanks David, I've been thinking about this. We are hosting the podcast on [Buzzsprout](https://www.buzzsprout.com/1997192/episodes), which enables you to embed a player like Soundcloud. My only question is exactly how Buzzsprout counts plays in their metrics. I think they count any play as a 'download,' but I don't know if that means only complete plays, or partial plays, I will check. If it is imprecise, we might benefit from hosting the audio file on our own website rather than using an embedded player on our own pages - while this would mean we would have to check our own site and Buzzsprout for complete info on engagement, it might give us richer data.

**Comment by Tim-Molyneux** [comment]
@davidebukali - update from Buzzsprout:

" In Buzzsprout a Download is registered anytime an audio file is requested from Buzzsprout and listened to for at least 60 seconds. This can happen when a listener hits play on an embedded player, Apple Podcasts, Spotify, or other podcast directories online or from any mobile app out there. It's all shown in Buzzsprout! 

    
 Our stats all follow the IAB Guidelines and you can check those out here: [Podcast Measurement Technical Guidelines ](https://iabtechlab.com/standards/podcast-measurement-guidelines/)

    
    If your website is able to determine more specific stats, you may want to host the files there. It's entirely up to you!"

I think that is we're able to host the files directly on our page so we can tell how far people are listening that would be quite useful, could we do that?

**Comment by davidebukali** [comment]
@Tim-Molyneux [this](https://www.analyticsmania.com/post/track-html5-audio-player-with-google-tag-manager/#how-to-track) guide uses Google Tag Manager(GTM). It says we are able to capture every 10% of the audio length; pause, play and finished events are supported. We could test using Buzzsprout and GTM and possibly get richer data from both platforms.
