### ISSUE TITLE
Anchor link functionality

### ISSUE THREAD

**Issue by LCowie** [devinit/DIwebsite-redesign#1249]
**Is your feature request related to a problem? Please describe.**
The anchor link function on the website isn't currently working but it would be a useful tool in current and future publications. We would usually expect to be able to insert an anchor without needing to select specific text, but rather a point on the page, exactly like the current footnote system.

**Describe the solution you'd like**
Please can the anchor link function be amended or recreated? As we'll be using the accordion function in some publications that will have anchor links, it would be great if anchor links could also be embedded in text within accordions. Can similar coding to that used to internally link footnotes in the CMS be applied to fix the accordion links?

**Describe alternatives you've considered**
The anchor block offers an alternative approach to linking text but using the block adds more spacing between sections in published format, which isn't always desirable. The anchor content block doesn't provide much more in the way of usefulness than the "Share section" links we already have.

**Requested Delivery Date:** 
As soon as possible as there are changes we want to make to recently published content.

**Comment by edwinmp** [comment]
The anchor link function is working as intended. It links to existing anchors. So I'd say this is an enhancement not a bug i.e. you need a better way to create anchors.

It's possible to inline an anchor within the WYSIWYG editor, but you'll still need to select specific text that a user will click on in order to jump to that anchor, and for this, you'll need the current anchor link feature. This won't be like the footnotes which are a single step process. So just to manage your expectations and to make sure we're on the same page, for anchors, you'll need to:

1. Create an anchor at a specific point on the page. This involves specifying a unique ID for that anchor. (this is what the anchor block does)
2. At some other point on that page, select text and use the anchor link functionality to turn that text into an anchor link by adding the anchor ID you used in step 1. When that text is clicked, it'll navigate to the configured anchor.

I can't promise that this will be a quick change since making updates to the WYSIWYG editor involves a lot of code. It's why StreamFields are preferred. I'll move it up and start on it asap.

**Comment by LCowie** [comment]
Many thanks Edwin, please let me know when those changes have been made.

All best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by edwinmp** [comment]
@LCowie  As I mentioned, this change would be a challenge and it's not disappointed ... been on it all week and it's a proper headache. Since you seem to need it urgently and I'll be on leave next week, I'll deploy what I've managed to get done which is mostly half-baked (but it works). I'll improve it later.

**Comment by edwinmp** [comment]
I've deployed the change on [dev](https://dev.devinit.org/admin/). Please note that this cannot work without selecting some text to attach the anchor to. I tried, it just doesn't work even if the anchored element exists.
Anyway, here's how it works.


https://user-images.githubusercontent.com/5672438/198530351-5a4d6006-5d0f-4fa8-8727-db1eedd6acdb.mov

Have a test and let me know if that's satisfactory. If so, I'll alert another team member to deploy it on Monday.

**Comment by edwinmp** [comment]
Point of improvement is that you cannot edit or smoothly remove the anchor as you would with the footnotes. You'd need to delete the text with the anchor and recreate it.

**Comment by LCowie** [comment]
Hi Edwin,

Many thanks for sending this video, the anchor link functionality seems better with this approach. Please can you deploy it on the live site?

All best,

Lucy

Lucy Cowie | Content & Publications Officer

I work Mondays, Tuesdays and Thursdays
Development Initiatives, First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK
T: +44 (0) 1179 272 505

At DI we value and respect flexible work arrangements. I choose to work flexibly and sometimes send emails outside normal working hours – no need to respond outside yours.
***@***.***

Read more about our work and its impact<https://devinit.org/what-we-do>
Development Initiatives is the trading name for: Development Initiatives Poverty Research Ltd, a not-for-profit company. Company No. 06368740 and DI International Ltd. Company No. 5802543, both registered in the UK.  Registered Address: First Floor Centre, The Quorum, Bond Street South, Bristol, BS1 3AE, UK.

**Comment by edwinmp** [comment]
@davidebukali will you let @LCowie know when this is live.

**Comment by davidebukali** [comment]
@LCowie this is now [live](https://devinit.org/admin/pages/2445/edit/)
