### ISSUE TITLE
Adding related pages 

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#304]
## I'm submitting a ...
Bug or question

**Describe the Issue**
The ability to add related pages at the bottom of a page does not appear to be consistent. Is there a reason that this is not an option for all pages?

**Comment by edwinmp** [comment]
Hi @alice-mcandrew-development-initatives This feature exists in two formats. The `More about` format is for most pages and only shows the hero & the title of the page.
![image](https://user-images.githubusercontent.com/5672438/67369799-5446f200-f582-11e9-82e7-6349e7081f2a.png)

Alternatively, we have the `Related page` format, and this is for blogs, news, publications, events because these can be configured to show more information depending on their content.

![image](https://user-images.githubusercontent.com/5672438/67369989-a0923200-f582-11e9-863d-24aff18fdb65.png)

As far as I can tell, all pages that'd benefit from having it have either of these.  The exceptions are listing pages, the home page, media page and maybe one or two I haven't discovered. A page shouldn't have both of these.

**Comment by jamesharle** [comment]
Thanks @edwinmp - so from a CMS point of view, on Who we are (for example), we have a text field and link selections to change the More about section. In Our team, which has an identical More about section in the pattern library, there is no such option on the CMS.

**Comment by jamesharle** [comment]
Thanks @akmiller01 - seeing no change on the CMS currently (sorry if you mean 'fixed' in a different sense...)

**Comment by akmiller01** [comment]
Yep. Fixed in code now, fixed on development server when merged, fixed on your staging site when we deploy it shortly.

**Comment by akmiller01** [comment]
Just deployed: http://159.65.56.142/admin/pages/6/edit/

**Comment by alice-mcandrew-development-initatives** [comment]
@jamesharle this seems to be working now

**Comment by jamesharle** [comment]
@akmiller01 this issue also applies to every team member profile.

**Comment by alice-mcandrew-development-initatives** [comment]
@jamesharle if this isn't resolved, I think we need to move it across to 'to do'...?

**Comment by akmiller01** [comment]
Resolved in code here: https://github.com/devinit/DIwebsite-redesign/pull/329

**Comment by edwinmp** [comment]
> Resolved in code here: #329

@alice-mcandrew-development-initatives this change has been deployed.
