### ISSUE TITLE
Admin password action causes 500 error

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#431]
http://159.65.56.142/admin/password_reset/

Chrome/Mac

#### Admin password action causes 500 error

No password reset email is sent.

![Screenshot 2019-11-18 at 14 15 11](https://user-images.githubusercontent.com/560463/69059679-e1f4f080-0a0d-11ea-99e0-fcfc03d933fc.png)

**Comment by k8hughes** [comment]
This is still not sending an email it is instead shows a page saying 'internal server error'

**Comment by k8hughes** [comment]
@edwinmp will this work once it is live or does it require more fixing?

**Comment by edwinmp** [comment]
@akmiller01 @Napho weirdly, the `DEFAULT_FROM_EMAIL` came through as blank (I had to manually set it in `.env`) ... any clue why? Also, this `os.getenv()` function doesn't consider the value of the env variable. It doesn't use the default value when the configured value is blank.
So I guess it's better to use `os.getenv('DEFAULT_FROM_EMAIL') or 'devinitautomailer@gmail.com'` instead of `os.getenv('DEFAULT_FROM_EMAIL', 'devinitautomailer@gmail.com')`

**Comment by edwinmp** [comment]
@k8hughes would need to do a restart to fix this, but I think there's plenty of activity on staging at the moment...

**Comment by Napho** [comment]
@edwinmp  .env is dropped every time a deployment is made and re-populated from travis

**Comment by edwinmp** [comment]
> @edwinmp .env is dropped every time a deployment is made and re-populated from travis

That's the mystery ... `DEFAULT_FROM_EMAIL` had no value after deploy... it was there in the `.env` but without the value set on travis.

**Comment by akmiller01** [comment]
@edwinmp any update on this? It works flawlessly on dev. And weirdly enough I did get the email on staging, but I got an internal server error page after submitting. Is it possible we've accidentally got a permanent redirect from that bad Debug Toolbar bug?
