### ISSUE TITLE
Data sets pulling through to cms but not appearing on page

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#508]
Something odd has happened with the datasets on this page (which has not happened consistently everywhere as far as I can tell, but I will note other examples if I find them): http://159.65.56.142/publications/is-the-201920-uganda-budget-pro-poor/

What the pages looks like:
![image](https://user-images.githubusercontent.com/55877063/69229482-62862f00-0b7d-11ea-8205-dc4cf55526db.png)

What the cms looks like:
![image](https://user-images.githubusercontent.com/55877063/69229521-7762c280-0b7d-11ea-9de3-f3e2b0cc2ae1.png)
^ These were not added manually and appear to have pulled through automatically

I'm not sure why this is happening.

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/569

**Comment by akmiller01** [comment]
As discussed with @AnnaHope , only Dataset Pages linked as Publication Datasets pull through. E.g. 
![image](https://user-images.githubusercontent.com/2836840/69971474-f517be00-14ed-11ea-9860-5970aa16f455.png)

Although the example above has lots of Figure Pages linked as Publication Datasets, none of them show because they're all figures.
