### ISSUE TITLE
No author meta on hero on guest blog article

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#519]
http://159.65.56.142/blog/future-humanitarian-transparency-assembling-big-picture/

Chrome/Mac

#### No author meta on hero on guest blog article

The [pattern library template](http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest) has a guest author module in the hero:

![Screenshot 2019-11-20 at 11 38 15](https://user-images.githubusercontent.com/560463/69236318-2ce84280-0b8b-11ea-95cd-2b3d66aafac5.png)

The [dev implementation](http://159.65.56.142/blog/future-humanitarian-transparency-assembling-big-picture/) does not have this present:

![Screenshot 2019-11-20 at 11 38 06](https://user-images.githubusercontent.com/560463/69236339-3671aa80-0b8b-11ea-909a-24fa85837b02.png)

**Comment by akmiller01** [comment]
In this particular case, there's no author so there's no link.

But in general, I think we need a CSS pull @edwinmp tried matching the markup exactly in https://github.com/devinit/DIwebsite-redesign/pull/523 (substituting an <a> for a <div> because it's reused in datasets), and it floats to the left instead of the right: 

Pattern library: 
![image](https://user-images.githubusercontent.com/2836840/69248487-61073780-0b7a-11ea-8032-ae2df9a00bc7.png)


Our page:
![image](https://user-images.githubusercontent.com/2836840/69248520-6ebcbd00-0b7a-11ea-972c-d60820bc1f1d.png)

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives I don't think we have any guest authors added to a blog yet.  Can you add one where it is appropriate to do so and then comment on the issue if there is still a problem or close it if you are happy?

**Comment by AnnaHope** [comment]
@akmiller01 @k8hughes The implementation on guest blogs is still wrong. 

Should be the pattern library - http://development-initiatives.surge.sh/page-templates/12a-blog-single-guest

![image](https://user-images.githubusercontent.com/16958942/69555863-bd63c000-0f9b-11ea-813a-ffabb4ebc6c8.png)


Instead we have: http://159.65.56.142/blog/people-want-building-resilience-stability-conflict-crises/
![image](https://user-images.githubusercontent.com/16958942/69555949-dec4ac00-0f9b-11ea-8cec-ede5b7bb94d7.png)


Moving back to 'to do'

**Comment by akmiller01** [comment]
@AnnaHope is the above comment about the authors or the hero_text? If it's about the hero_text, it's simply a matter of removing the text from the hero_text field and adding it as a paragraph to the body.

If it's a matter about the guest authors, that's how the pattern library displays multiple authors. If you remove one author and leave only a guest author remaining, it should match the pattern library. 

I think we will still need to separate this author-link include from the one used in the data section, since that requires an <a> and that seems to break the size of the single author.

**Comment by akmiller01** [comment]
Scratch that, the mark-up is still exactly the same. @edwinmp any clue on why the CSS for staging is still creating such a small author link?

On staging:
![image](https://user-images.githubusercontent.com/2836840/69557654-fa688c00-0f74-11ea-86c9-7f23fb242d6d.png)
 
On surge:
![image](https://user-images.githubusercontent.com/2836840/69557696-081e1180-0f75-11ea-9a4a-2c1163abb0cb.png)

**Comment by akmiller01** [comment]
Here's a concrete example @edwinmp http://159.65.56.142/blog/blog-blended-finance-impact/

**Comment by alice-mcandrew-development-initatives** [comment]
Hi @akmiller01 , this isn't a guest blog: http://159.65.56.142/blog/blog-blended-finance-impact/
But, this is: http://159.65.56.142/blog/people-want-building-resilience-stability-conflict-crises/

**Comment by akmiller01** [comment]
Cheers @alice-mcandrew-development-initatives , it shouldn't matter as they're using the same markup.
