### ISSUE TITLE
Rich text editor has footnotes feature on page template that doesn't support footnotes

### ISSUE THREAD

**Issue by urlsangel** [devinit/DIwebsite-redesign#524]
http://159.65.56.142/admin/pages/636/edit/

Chrome/Mac

#### Rich text editor has footnotes feature on page template that doesn't support footnotes

This is on the job vacancy page, but may be on others around the site.

Rich text features can be controlled on a per-instance basis, so it's misleading/confusing to include the functionality on a page template that doesn't support footnotes such as job vacancies.

Would recommend reviewing all rich text instances and removing where not supported.

![Screenshot 2019-11-20 at 14 39 54](https://user-images.githubusercontent.com/560463/69248161-a8ee8480-0ba3-11ea-833b-e6bc6f8d2eef.png)

**Comment by akmiller01** [comment]
https://github.com/devinit/DIwebsite-redesign/pull/567

**Comment by edwinmp** [comment]
@akmiller01 I think this required more extensive application i.e. I don't think heroes need footnotes, or downloads or banner block text ... hmm, perhaps the better question is which pages support footnotes? I think it's a smaller list.

**Comment by akmiller01** [comment]
@edwinmp already removed footnotes from most editors. Check #567 , I swapped the richtext features all over to the versions without the footnotes. Only publications and blogs have them now.

**Comment by edwinmp** [comment]
@akmiller01 yeah, but there's richtext fields that weren't making use of the `RICHTEXT_FEATURES` constant ... those still have the footnotes.

**Comment by alice-mcandrew-development-initatives** [comment]
This seems to be a problem for legacy pages.
E.g. http://159.65.56.142/publications/preliminary-oda-data-2018-total-falls-for-second-consecutive-year/
This is what the CMS looks like:
![CMS](https://user-images.githubusercontent.com/55877063/69622842-a4a9e780-1039-11ea-9917-d940ae615ac1.JPG)
This is what the live page looks like:
![Live page](https://user-images.githubusercontent.com/55877063/69622855-aa073200-1039-11ea-85f9-66fc3bcf7a44.JPG)

(I had to re-create this page, because it had sections when it shouldn't, so it's not the content that was migrated over. I can re-create this as a short publication, without sections, and see if that works).

**Comment by alice-mcandrew-development-initatives** [comment]
The same doesn't apply to short publications so it shouldn't be a problem ^

**Comment by akmiller01** [comment]
Fixed this in case we want footnotes on legacy pages in the future: https://github.com/devinit/DIwebsite-redesign/pull/590
