### ISSUE TITLE
Related content - not appearing on publications page 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#642]
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x ] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
A clear and concise description of what the issue is.
The publications pages have the option to add 'Related content'; however when this is added, it doesn't appear
![image](https://user-images.githubusercontent.com/22001094/70707074-3a4aa580-1ccf-11ea-92bf-7389e1b2ad88.png)

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
1. Go to '...' https://159.65.56.142/admin/pages/1316/edit/
2. Click on '....' Add related content (lowest option in the CMS on that page 
3. Scroll down to '....' Select and add the relevant page 
4. See error - the content doesn't appear at the bottom of the live page 

**Expected Behaviour**
A clear and concise description of what you expected to happen

See the page design for expected 'related content' behaviour
https://development-initiatives.surge.sh/page-templates/14-1-publication-long-form

**Screenshots/GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [ ] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by SimonMurphyDI** [comment]
Hi there @edwinmp  - I still can't see this on page for short publications? Would love to have it deployed :)
Cheers
Simon

**Comment by edwinmp** [comment]
Hi @SimonMurphyDI this should be fixed.

**Comment by SimonMurphyDI** [comment]
Comms review - this is fixed; however, the order of the three bits of related content is always the order you add them: these arrows don't allow you to re-order:
![image](https://user-images.githubusercontent.com/22001094/83010694-8fc20700-a010-11ea-863b-ac070fa53aaa.png)

**Comment by edwinmp** [comment]
@SimonMurphyDI you're right ... reordering them doesn't persist on publish ... will look into it.

**Comment by edwinmp** [comment]
@SimonMurphyDI the ordering issue is now fixed.

**Comment by SimonMurphyDI** [comment]
it is, and we're chuffed. thanks :)

**Comment by alice-mcandrew-development-initatives** [comment]
Hello @edwinmp (FYI @k8hughes), I've added related content to the GHA Report 2020 Executive summary in the CMS but it does not appear on preview.

- CMS: https://devinit.org/admin/pages/2100/edit/
- Preview: https://devinit.org/admin/pages/2100/view_draft/

(This is particularly odd because it does work for Chapter 1: https://devinit.org/admin/pages/2101/view_draft/)

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives summary pages are not supposed to have related content (as per the PL), so the error here is in the CMS having a provision for it. It's also probably why we've never caught it before since this has been like this from the beginning.
https://development-initiatives.surge.sh/page-templates/14-publication-summary

**Comment by alice-mcandrew-development-initatives** [comment]
Thanks, @edwinmp. I had forgotten this. Apologies! I have reminded the rest of the Communications team also now.
