### ISSUE TITLE
No publications pages are displaying initial section of content correctly

### ISSUE THREAD

**Issue by AnnaHope** [devinit/DIwebsite-redesign#663]
All the content on our publications starts very far down the page, and a) isn't as the template shows but b) could impact user experience as you can't see that there is an HTML version of the publication below the header.

Can this pleased be sorted as a priority? It really doesn't look great. Thanks!

How it is now on short publications:
![image](https://user-images.githubusercontent.com/16958942/73546143-9bbc0480-4434-11ea-85a7-843cb1d18c96.png)

How it should be:
![image](https://user-images.githubusercontent.com/16958942/73546184-ad051100-4434-11ea-81a0-7884215aeb05.png)

How it is now in long publication summary:
![image](https://user-images.githubusercontent.com/16958942/73546274-dc1b8280-4434-11ea-8569-cfdf7a3cbd60.png)

How it should be:
![image](https://user-images.githubusercontent.com/16958942/73546299-e6d61780-4434-11ea-8118-0a51ca88a433.png)

@k8hughes FYI - not sure how workflow is being managed but I think leftover problems with the website that impact user experience need to be addressed fairly quickly and certainly not left for over 2-3 weeks really.

**Comment by akmiller01** [comment]
Fix here. Will require some testing on dev before we push it live: https://github.com/devinit/DIwebsite-redesign/pull/664

**Comment by akmiller01** [comment]
Some tests by @davidebukali @AnnaHope I wasn't able to get the Short Publication 100% like the template, because they've buried the author block deep into the content and it would take a pretty major refactor of `templates/publications/blocks` to make sure it all works out. So the Short publication author is a bit wider than in the pattern library, but if it works as a hotfix we can de-priorize the bigger refactor. David's screenshots below:

Short:

![short2](https://user-images.githubusercontent.com/2836840/73554219-53431d80-4419-11ea-8ef0-c431a773c75b.png)

Full:

![full2](https://user-images.githubusercontent.com/2836840/73554255-67871a80-4419-11ea-9baf-667234c76b0a.png)

Legacy:

![legacy_publication](https://user-images.githubusercontent.com/2836840/73554283-72da4600-4419-11ea-9af2-32e09cbde519.png)
