### ISSUE TITLE
Compare locations - area charts can be confusing

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#694]
When looking at a comparison between two areas, Kiambu and Nyeri, looking at Population > Number of Households (see image below) it could appear that Nyeri has over 600k, when in fact it's actually about 200k. I think this is because we're using area charts. A line chart would be clearer. 

I think as a rule of thumb, if we have data over a number of years then we should use line charts. If we have data for a single year then a bar chart would be better. 

<img width="1343" alt="Screenshot 2020-03-26 at 14 14 36" src="https://user-images.githubusercontent.com/64877/77657997-f3c34300-6f6d-11ea-879d-3d07b64a458d.png">

**Comment by k8hughes** [comment]
@edwinmp this seems to make perfect sense.  Do you want me to make an issue for this in the spotlights repo?

**Comment by edwinmp** [comment]
@benjamincoleman @k8hughes Yeah, Moses & Eastone opted for the line chart as well after testing with both ... I made the change yesterday ... will deploy asap :)

I found area charts to be easier to understand when comparing multiple years & for the purpose of seeing a general trend (rising or falling over the years). With line charts, you tend to see a criss-crossing of lines. I like the description in this article https://www.edrawsoft.com/chart/when-to-use-area-chart.html 

> A stacked area chart is best used to show distribution of categories as parts of a whole, where the cumulative total is unimportant.

On that note, I want to inquire on whether it's a good idea to have the line chart as a default but give the user the ability to switch between line, area & bar charts. Programatically, it'd be easy. I guess I'm saying `power to the people`... hehe

**Comment by k8hughes** [comment]
I think we can't include the area chart as the data isn't cummulative, but maybe the bar chart is ok?

**Comment by edwinmp** [comment]
A stacked area chart is cumulative by default, which is what @benjamincoleman pointed out as confusing. It is excellent for viewing general trends while still being able to see the disparities between the individual parts.

**Comment by edwinmp** [comment]
@akmiller01 I'd love your input on this

**Comment by akmiller01** [comment]
> @akmiller01 I'd love your input on this

What data vis we pick depends on what the key message we want to display. I don't think an area chart here is appropriate, because our key message isn't "Look at how the sum of two districts has changed over time." If we were visualizing every district simultaneously, then the sum of the population figures would be a meaningful "National population" and you could see how each district contributed to the national figure. But this case, the sum of two districts is relatively meaningless.

I would actually advocate for a grouped bar chart like so: https://google.github.io/charts/flutter/example/bar_charts/grouped_full.png

Lines imply continuous data, and more often than not we only have annual data (and sometimes gappy annual data). Bars express this discreteness better, and fill up the chart space with a lot more colour than lines.

**Comment by edwinmp** [comment]
> On that note, I want to inquire on whether it's a good idea to have the line chart as a default but give the user the ability to switch between line, area & bar charts. Programatically, it'd be easy. I guess I'm saying `power to the people`... hehe

@akmiller01

**Comment by akmiller01** [comment]
> > On that note, I want to inquire on whether it's a good idea to have the line chart as a default but give the user the ability to switch between line, area & bar charts. Programatically, it'd be easy. I guess I'm saying `power to the people`... hehe
> 
> @akmiller01

Do we have any data on how often people actually played with the toggles on those scatterplot visuals we used to have on the DataHub? Usually I would be okay with giving the users a choice, but I think that sometimes it can over-complicate things...

**Comment by edwinmp** [comment]
A lot of the feedback we got from users was how little control they had on the type of visualisation they saw ... We're living proof of that ... we can't even agree which would be better between a line, bar & area because we're looking for different things out of this data.

> Usually I would be okay with giving the users a choice, but I think that sometimes it can over-complicate things...

Having a default (line chart) removes the complication I think. They don't have to change it if they don't want to.

**Comment by edwinmp** [comment]
> What data vis we pick depends on what the key message we want to display.

This worries me ... should it be about us? :)

**Comment by akmiller01** [comment]
In that case, it sounds like a good idea to give users choice.

Would it over-complicate things to vary the default depending on the data-types and/or data quality? If you have a point in 2004, and a point in 2010, I would say defaulting to a line chart that draws a straight line from 2004 to 2010 would be disingenuous.

Also, about the "about us" question, visuals definitely need some sort of default messaging, otherwise they're not informative. If we give users control over the chart type, it would allow us to set a default message, while allowing users to create their own conclusions.

**Comment by edwinmp** [comment]
> Would it over-complicate things to vary the default depending on the data-types and/or data quality? If you have a point in 2004, and a point in 2010, I would say defaulting to a line chart that draws a straight line from 2004 to 2010 would be disingenuous.

Interesting point ... programatically, not complicated ... better yet, we could configure this default in the CMS for each indicator. That should give us plenty of choice in the messaging.

**Comment by k8hughes** [comment]
This is a good conversation to catch up with, it sounds like you have a good implementation plan and then for setting the default charts we'd want to run through it with Eastone, Moses and Alex so we can be clear what is the most informative choice in every case.

**Comment by k8hughes** [comment]
Do we still need to have this issue open or have we resolved it?

**Comment by k8hughes** [comment]
@edwinmp I think we can close this, can you check and confirm?

**Comment by edwinmp** [comment]
Created a feature request for this, so yeah, I'll close it.
