### ISSUE TITLE
T24 - Data tools page

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#752]
Currently set up as this template: http://development-initiatives.surge.sh/page-templates/24-country-spotlights

Will need to change it's name to 'Data Tools' as there are more than just the spotlights here.

Sketch: https://marvelapp.com/3j51290/screen/69215526

For each 'tool' we have a module that includes: 

1. Title
2. Content - 150 words as a guide, use the real content for the spotlights please
3. Image
4. Button, or buttons, to link through to the tool(s)
5. An example where we use a video instead of an image

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the design for this template to include the above changes, most of this is using modules we already have but there is one minor note for the use of video instead of an image in the `banner` module, we really need to add a modifier class of banner__media--video to the banner__media element so we can control the width and height of the embedded video like we do we the `media-video-wrapper` class used elsewhere. You can see the design here: http://development-initiatives.surge.sh/page-templates/24-data-tools

**Comment by benjamincoleman** [comment]
> we really need to add a modifier class of banner__media--video to the banner__media element so we can control the width and height of the embedded video like we do we the media-video-wrapper class used elsewhere. 

@BenDarby do you mean we have done this and that the dev team need to be aware of this?

**Comment by benjamincoleman** [comment]
@BenDarby on this one, can you alter the way it stacks on mobile for this page only. 

Ideall we want the order to be: 

1. Title
2. Text
3. Buttons
4. Image / Video

I know that might need duplication of the buttons in the DOM and some showing / hiding, but the flow will be much better.

**Comment by BenDarby** [comment]
@benjamincoleman yeah sorry, I have added the modifier class to the element for the video on the PL so it just something for the dev team to be aware of. I'll update mobile stacking and yeah we'll need to duplicate the buttons

**Comment by BenDarby** [comment]
@benjamincoleman I have updated the stacking of elements on mobile to reflect the order mentioned above

**Comment by benjamincoleman** [comment]
@BenDarby Thanks Ben - looks great now.
