### ISSUE TITLE
Pop up picture feature from GNR

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#773]
Pop up picture feature from GNR, a bit of code was generated that lets users ‘pop’ an image out, and then zoom in to look at a section. You can see it in action here.  
https://globalnutritionreport.org/reports/2020-global-nutrition-report/inequalities-global-burden-malnutrition/ 
It would be possible to transition the same code to the DI site. 
It looks like this issue:  https://github.com/devinit/gnr-website/issues/52 
But there isn’t a linked pull request.
@urlsangel  could you point us in the right direction please?

**Comment by urlsangel** [comment]
Hi @k8hughes @edwinmp 

This functionality was achieved by adding a link around the infographic `<picture>` element which refers to the `wide` format of the picture (the largest), and opens the link in a `_blank` window.

The `<a>` tag was added here: 
https://github.com/devinit/gnr-website/blob/master/content/templates/content/blocks/infographic.html#L16

You can see the diff here: 
https://github.com/devinit/gnr-website/commit/76b9b3ee2ce6d0aec3ae18cf1573e455de493e84#diff-8c737bc495d81dc616d63267462212f7

As far as I can tell, you'd want to add the same code here:
https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/blocks/basic_infographic.html#L17

**Comment by k8hughes** [comment]
@davidebukali this could be a good one for you to look into.

**Comment by davidebukali** [comment]
@k8hughes this was deployed to staging, please have a look when you are free

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives   I wasn't sure where to test this - could you take a look?
I checked this report http://178.128.102.213/resources/food-poverty-global-regional-and-national/ 
Then clicked on the figare and it pops out here:  http://178.128.102.213/media/images/Fig_1.width-1200.png 
It would be good to know from you if that is what you wanted...

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes I've tested it here: http://178.128.102.213/resources/global-humanitarian-assistance-report-2019/executive-summary/. I can't think of anywhere else where we have a graphic with this much detail so it's probably the best example.

@davidebukali I agree with Kate: the zoom function works very well. Thank you! 

@k8hughes I notice that the resolution doesn't appear great on the example I tested when you zoom in, as well as in a few other instances. It seems we (Comms) will need to be more careful about how we balance resolution for quality of appearance vs load speed now that we have this additional functionality. But that's something for us rather than you. Although any technical advice or suggestions would be appreciated as always if you have any! It seems (from the above) it will be the wide version of the image that the pop-up uses so perhaps it's that this in particular needs to be high-res but narrow/medium is less of a concern.

Also, I took a look at this blog: http://178.128.102.213/blog/data-universal-health-coverage-kenya/.
This confirms that the zoom works for 'infographics' (aka charts) but not images in general, which is, of course, very logical. I'm vaguely aware that the ability to insert infographics into blogs is in the pipeline though and presumably once that change is in place we will be able to zoom in on charts in blogs also?

**Comment by k8hughes** [comment]
@davidebukali will this work for charts in blogs?
@alice-mcandrew-development-initatives are you happy to approve this for deployment?

**Comment by davidebukali** [comment]
@k8hughes I added an issue for charts in blogs #803

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes yes
@SimonMurphyDI FYI
