### ISSUE TITLE
Changes to the foreword in reports

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#774]
The current website functionality does not allow for any content to appear before the executive summary module however we'd like to have a forward first  – I know that GNR website was updated so foreword was optional so may be fairly straightforward if we have that code already.

@urlsangel could you point us in the right direction so we can grab this code from GNR?

**Comment by urlsangel** [comment]
Hi @k8hughes @edwinmp 

The foreword was added in this commit:
https://github.com/devinit/gnr-website/commit/8857ff106691c51aa2422aa24bea55bd11a24bd9#diff-44bff827b72d070a8094405a29be021a

It was then also added to the home page listing here (not sure if that is relevant for the DI site though):
https://github.com/devinit/gnr-website/commit/714105ab11ccc1683dd2197264780480173f1945#diff-44bff827b72d070a8094405a29be021a

The `ReportForewordPage` type is essentially a clone of the `ReportSummaryPage` type - there are a number of places in the code where an optional foreword is added to the listing etc. if one is created and is 'live' (as with the summary page type).

It's probably worth Edwin reviewing the `reports/models.py` and associated files in the first commit referenced above to see where these changes need to be implemented in the DI site.

This task may need a bit of back and forth, so please feel free to give me a shout if you need to.

**Comment by k8hughes** [comment]
@davidebukali This could be a good one for you to look into

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp @davidebukali Also, let me know if you want the pattern library updated.

**Comment by k8hughes** [comment]
@alice-mcandrew-development-initatives I'm passing this one over to you to test as I'm not sure where to go in the CMS to edit reports, can you check that the forward is working as intended?

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes and @davidebukali 
I've tested here: http://staging.devinit.org/resources/global-humanitarian-assistance-report-2019/

1) Please can we have the buttons on the parent page as lower-case for consistency with other modules:
![image](https://user-images.githubusercontent.com/55877063/85423351-82942b80-b56e-11ea-841d-b038b76e0586.png)

2) Please can we have the option to have the foreword in different colour. It looks like this on other child pages: 
![image](https://user-images.githubusercontent.com/55877063/85423913-2ed61200-b56f-11ea-9b51-d61822514ee9.png)

3) Please can it be 'FOREWORD' in the menu (across all relevant pages) rather than 'THE FOREWORD'. We can remove 'THE' for the executive summary also:
![image](https://user-images.githubusercontent.com/55877063/85423636-d868d380-b56e-11ea-8cd9-0a4c9a9b5a65.png)

4) I am getting some odd text appear on the foreword page and I can't see where it's come from:
![image](https://user-images.githubusercontent.com/55877063/85423733-f33b4800-b56e-11ea-99e1-5483d6c382cb.png)
The content I've added in the cms doesn't seem to be appearing:
![image](https://user-images.githubusercontent.com/55877063/85423777-051ceb00-b56f-11ea-9637-8744ec99e2c0.png)

5) On the foreword page, 'Publication downloads' should be sentence case (so not 'Publication Downloads'):
![image](https://user-images.githubusercontent.com/55877063/85424067-6218a100-b56f-11ea-9824-5513224d1f81.png)

**Comment by k8hughes** [comment]
I'll move this back to `to do` as there is now some feedback to work  on

**Comment by davidebukali** [comment]
@alice-mcandrew-development-initatives we have deployed updates for your comments above, please take a look when you get the chance

**Comment by alice-mcandrew-development-initatives** [comment]
Looks good! Thanks @davidebukali (and thanks @k8hughes for the prod!)

**Comment by alice-mcandrew-development-initatives** [comment]
@k8hughes and @davidebukali, I have just noticed there is no option to add related links to the Foreword module. 
For example, the GHA Report 2020 Foreword: https://devinit.org/admin/pages/2099/edit/ 
Please can we add this functionality?

**Comment by alice-mcandrew-development-initatives** [comment]
@davidebukali The related links look good, thank you. However, I've realised that for the GHA Report 2020, the Foreword does not have the call to action module which other child pages are pulling through: 
![image](https://user-images.githubusercontent.com/55877063/88182594-4b29a500-cc28-11ea-8043-2d609e16e6a7.png)

See here: https://devinit.org/resources/global-humanitarian-assistance-report-2020/foreword/

**Comment by edwinmp** [comment]
Ah, sorry @alice-mcandrew-development-initatives we forgot about the Foreword as its a new type of page ... the call to action should be pulling through on all other child pages

**Comment by alice-mcandrew-development-initatives** [comment]
Can we amend so that this for future pages @edwinmp? We may used a call to action module again, as it seems a useful/versatile feature.

**Comment by alice-mcandrew-development-initatives** [comment]
(And also for the GHA Report 2020 if possible)

**Comment by edwinmp** [comment]
Definitely fixing for the Foreword... will let you know when deployed for testing.

**Comment by edwinmp** [comment]
I'm adding it to AudioVisualMedia pages as well ... they seem to fall under publications.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives a fix for this has been deployed to staging

**Comment by alice-mcandrew-development-initatives** [comment]
@edwinmp It looks good! Thank you

**Comment by alice-mcandrew-development-initatives** [comment]
Hi @davidebukali or @edwinmp, I've noticed that the 'data downloads' section of the cms on the GHA Report 2020 Foreword is pulling through publication download snippets:
![image](https://user-images.githubusercontent.com/55877063/88544479-5c502880-d011-11ea-9b25-70eb8c4b112f.png)

**Comment by edwinmp** [comment]
> Hi @davidebukali or @edwinmp, I've noticed that the 'data downloads' section of the cms on the GHA Report 2020 Foreword is pulling through publication download snippets:

@alice-mcandrew-development-initatives a fix for this is deployed on staging http://staging.devinit.org/admin/pages/2034/edit/

**Comment by alice-mcandrew-development-initatives** [comment]
Looks good! Thank you

**Comment by alice-mcandrew-development-initatives** [comment]
^ Sorry, should have tagged you @edwinmp

**Comment by alice-mcandrew-development-initatives** [comment]
Sorry @edwinmp and @k8hughes I've now noticed it also doesn't have the report download section at the bottom.

**Comment by edwinmp** [comment]
> I've now noticed it also doesn't have the report download section at the bottom.

@alice-mcandrew-development-initatives this has been added to staging ... please have a look.

**Comment by k8hughes** [comment]
As Alice is off this week could either @SimonMurphyDI or @jamesharle check this one over for us?

**Comment by SimonMurphyDI** [comment]
looks great!
