### ISSUE TITLE
T26 - Interactive visualisation

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#799]
We need a template to show a single interactive visualisation.

This template is non-public, and is intended for the creation and review of interactive visualisations in Wagtail by editors. 

We've been working on the design in the context of a publication here: #781 

There's a sketch for this template here: https://marvelapp.com/3j51290/screen/70492428

**Comment by BenDarby** [comment]
@benjamincoleman  I have added this template to the PL which can be seen here https://di-vis.surge.sh/page-templates/26-interactive-visualisation

**Comment by benjamincoleman** [comment]
@BenDarby design updates for this piece of work. 

**Fallback image**

This has got a little more complex, so I'll walk through the issues in play: 

1. When we have no JS we'll show the image. 

2. When we have JS but the window is smaller than:
    - X (small screens)
    - Y (medium screens)

    These should be controlled with two separate classes to make them content manageable.

3. We want the image to not download when not required. You'll need to research this to find a solution. 

4. The image should be clickable and link to the image asset itself (what we did on GNR) as this helps folks with small screens.

5. We'd like a piece of text to go with each fallback image option: 
    - No JavaScript > “To view an interactive visualisation make sure JavaScript is available on your device.”
    - Small screen > “To view an interactive visualisation use a device with a larger screen.”

6. We need a loading animation before the chart loads. This would have a class of 'loading' or something, and do two things: 
    - Animate using CSS - something spinny?
    - Force a min-height to mitigate against the jump of something loading in

**Comment by urlsangel** [comment]
@benjamincoleman @BenDarby 

Will we have just one optional rich text area at the beginning of the accordion tray content, followed by one optional definition list, or are you seeing them as mix and match in terms of numbers created and position?

**Comment by benjamincoleman** [comment]
One rich text area at the top, optional DL below.

**Comment by benjamincoleman** [comment]
@BenDarby a bug has come about from the accordion - if it's not present (which could happen) there's a problem with vertical spacing on the caption. 

Edwin describes this here: https://github.com/devinit/DIwebsite-redesign/issues/781#issuecomment-651093580

If you can update him when that is fixed that would be great.

**Comment by BenDarby** [comment]
@benjamincoleman @urlsangel I've done some work to this, and I needed to adapt a little from the above because I don't think we could have achieved everything we wanted. 

As `display: none;` isn't suitable for the fallback due to the image still being loaded I thought about using a background image as that article suggested a background image with `display: none;` doesn't load the image, the main issue here is we wouldn't be able to click the to view image in a new tab. The article suggested using JS to hide the `img` element in the DOM but this didn't seem like a good idea due to it needing to work without JS.
So I did some research and came across another article using the `picture` element and `srcset` I thought this would be a good solution as we wouldn't need to mess around with lots of classes and can use the native `srcset` functions to serve a different image for mobile and medium screens, similar to GNR charts. Then we have the final `srcset` at `601px` where we serve a base 64 encoded 1px transparent png, this still causes the browser to download an image but it's tiny and doesn't affect page load, looking at the network tab in inspector it's 0ms. 
I thought this solution works best as we can still allow them to upload a different image for mobile and medium screens, which will also be the fallback and can be clicked to view it in a new tab. This all will work the same way as publication charts :) 
I've added some markup for the right text to appear depending on the fallback image or mobile images showing. I also added a spinner, if you add a modifier of `chart-container--loading` this will show the spinner.

And finally, I updated the accordion content to include rich text copy above the icons. 

Let me know if this all sounds good to you and if there's amends I can look at them in the evening.

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Cheers for the update @BenDarby - I've implemented the loading bit locally, but just wanted to flag up that the `<picture>` solution detailed above will still download the `<img>` in IE11 - @benjamincoleman is this an issue?

I can think of another way to do this - it's JS dependent, but that's ok as that's necessary for the chart anyway.

A rough outline would be:

#### Non-JS fallback image with link
This would be an `<a>` tag with a link to the full image, with the image set as a background. This would be set to `display: none` if the `.js` class is present on the `<html>` tag.

#### JS available fallback image with link
The above `<a>` element can contain `data` elements for the `narrow`, and `medium`, and `full` image urls - this can then be converted to a `<picture>` with the required `<src>` elements at JS render time, with the chart itself only being rendered at the appropriate screen width.

**Comment by benjamincoleman** [comment]
I'm not fussed about IE11 - there are very few visitors using that tech. 

You missed one requirement which will need adding: 

> Force a min-height to mitigate against the jump of something loading in

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Implemented a solution on this template: https://di-vis.surge.sh/page-templates/26-interactive-visualisation

**Comment by BenDarby** [comment]
@benjamincoleman I've added some spacing between title and fallback image and increased the contrast on the alerts. Point 2 seems to have been done already :)

**Comment by benjamincoleman** [comment]
@BenDarby One more edit - can we move the chart dropdown as follows: 

.chart-container .data-selector {
    top: 0.5em;
    left: 0.5em;
}

It then lines up with the plotly controls on the right side.

**Comment by BenDarby** [comment]
@benjamincoleman updated and pushed

**Comment by benjamincoleman** [comment]
@urlsangel for controlling this:

1. Checkbox "display fallback image on mobile", default is checked
2. Checkbox "display fallback image on tablet", default is unchecked
