### ISSUE TITLE
T16 Team stories should have link

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#80]
Each of the departments listed should be a link

**Comment by benjamincoleman** [comment]
@BenDarby can't see this as being done. 

These should be links:

![Screen Shot 2019-07-11 at 12 53 38](https://user-images.githubusercontent.com/64877/61048844-efa0c680-a3da-11e9-9868-bbd2266aaffc.png)

**Comment by BenDarby** [comment]
@benjamincoleman the titles are links

**Comment by edwinmp** [comment]
Hi @benjamincoleman, I've encountered this in issue #20 and I'm wondering how these logos would be added. I'd wanted to be able to do this dynamically, just automatically pull in all the child pages of `work for us` and show them here... the problem is the logos. Which leaves only the option of manually selecting a logo (probably a drop-down list of existing ones), and then attaching a page. Any ideas?
