### ISSUE TITLE
Change to how anchor links are added 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#805]
## I'm submitting a ...
<pre><code>
[X] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When trying to add anchor links to a page (using the option in the editor), the anchor link button creates 'href' rather than 'id' so the links don't function. 

**To Reproduce**
1. Go to a publication or resource and try to add an anchor link - it doesn't function. Alex explained this is because the  the anchor link button creates 'href' rather than 'id'

**Comment by akmiller01** [comment]
Hi @edwinmp Simon asked me about this one in the first place. You are correct in guessing that Simon is asking for the ability to place an anchor (something like `<a id="arbitrary-id"></a>`) via the WYSIWYG.

Given the fact that linking to pre-existing anchors was added to the standard link button, I thought it would make the most sense to refactor our old anchor link button to create `<a id=` instead of `<a href=`.

The existing anchor is created as a combination of this wagtail hook https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/publications/wagtail_hooks.py#L14-L68 and this bit of React https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/common/static/common/js/anchor.js

Theoretically it should be as simple as swapping out mentions of `href` in the hook and JS to `id` but I gave that a quick try and it seems like `id` is a protected namespace (reserved for giving anchors the ID number of a page for an internal link), and I couldn't figure out how to work around that.

If it's not possible to add to the WYSIWYG editor by extending Draftail, our only other option is to add it as a block to the StreamField.

**Comment by edwinmp** [comment]
@SimonMurphyDI added a StreamField - `anchor`. Add it before the content you want the navigate to.

![image](https://user-images.githubusercontent.com/5672438/86365346-11e1c300-bc82-11ea-8b33-cc8f14c792c6.png)

![image](https://user-images.githubusercontent.com/5672438/86365546-50777d80-bc82-11ea-91ab-374f594317fb.png)

**Comment by SimonMurphyDI** [comment]
I still don't understand how to make this work so can't test the functionality

**Comment by edwinmp** [comment]
Step are as follows:

1. Add an anchor to the place you want to navigate to - make sure the Anchor ID is unique
![image](https://user-images.githubusercontent.com/5672438/87923057-92c3fb80-ca85-11ea-8465-79170c37ec0c.png)


2. In a RichText block somewhere, add an anchor link, with the ID(#) set to the one you created in step 1
![image](https://user-images.githubusercontent.com/5672438/87923268-e46c8600-ca85-11ea-8e15-76a5f70b3247.png)

**Comment by SimonMurphyDI** [comment]
Looks great!
