### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#827]
Test on devices

**Comment by urlsangel** [comment]
@BenDarby @benjamincoleman 

Safari has a ton of whitespace at the top of the publication page, it's occurring on my local production and the PL template:

https://di-vis.surge.sh/page-templates/14-1-publication-long-form

<img width="1440" alt="Screenshot 2020-07-07 at 09 49 38" src="https://user-images.githubusercontent.com/560463/86752576-5d57f080-c037-11ea-94f5-8a77d0828367.png">

**Comment by urlsangel** [comment]
@benjamincoleman 

Browser/device testing complete on Mac/Windows/Devices - all good except for IE11, which has issues with modern ES6/7 JavaScript.

I'd thought that this would be supported by the production webpack build([based on this conversation here](https://devinitorg.slack.com/archives/CCJDWJ669/p1592921914010800?thread_ts=1592919063.005800), but it turns out it's not currently.
