### ISSUE TITLE
Private publish function does not appear to be working

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#831]
The publish privately function doesn't appear to be working on the website at the moment. For example, in the resources section, when you attempt to publish the GHA Report 2020 privately it appears live to general public also. 

It's going to be problematic for checking the GHA Report 2020 pages (which we need to do end of w/c 13 July) if we can't privately publish, as you can't check the appearance of the parent page if you just save drafts and preview.

**Comment by edwinmp** [comment]
@alice-mcandrew-development-initatives this has been deployed. Could you please test on staging.

**Comment by SimonMurphyDI** [comment]
@edwinmp - I just created a test page that was published privately. I could see it appear on the resources listing page, but when I opened the same link in an incognito browser, it wasn't visible. 
Likewise, the page at the specific resource url is visible on the staging site, but asks the user to log in on the incognito browser. 
I think this is all the expected behaviour we wanted, so it looks good to me!
