### ISSUE TITLE
Improving the data for download section - part two

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#879]
We need to get a signle work book of data for each spotlight  - I am assuming this can be done from DDW?

We may then need to collect the metadata - I'm not sure if it is on the spotlights to the level of detail that we need.

These can then be added to the data section along with all the publication workbooks.

**Comment by akmiller01** [comment]
[Spotlight_on_Kenya.xlsx](https://github.com/devinit/DIwebsite-redesign/files/5036246/Spotlight_on_Kenya.xlsx)
[Spotlight_on_Uganda.xlsx](https://github.com/devinit/DIwebsite-redesign/files/5036247/Spotlight_on_Uganda.xlsx)

Please see above for some automated outputs. I tried to use a version of @SimonMurphyDI 's cover page, but it seems like it's mainly for individual figure sheets rather than datasets. Maybe we need to amend the cover sheet format?

**Comment by k8hughes** [comment]
I have sent an email so we can work out the right format for this data in terms of how we present it in the data for download section.

**Comment by akmiller01** [comment]
After speaking with Moses, I think we've concluded that we need to balance ease of data access and reduction of clutter on the site. Some concrete changes to implement that would help achieve this.

- [ ] Remove purely mechanical datasets (website colors, etc)
- [ ] Join human-readable codes to codelists where possible (district id -> district name)
- [ ] Split data into thematic XLSX files (instead of one big XLSX, or dozens of single CSVs, e.g. Health, Finance, Education)

**Comment by k8hughes** [comment]
Moses has made this into a nice set of workbooks, we're just waiting for him to add the new data then there will be something for Uganda at least to add to the website, we'll need to wait for Eastone's return to do the Kenya data.

**Comment by k8hughes** [comment]
Simon added this data to the website.
