### ISSUE TITLE
Extra information on our podcast pages 

### ISSUE THREAD

**Issue by sarahharries66** [devinit/DIwebsite-redesign#937]
We're looking to add some more features to our podcast pages to help give out a bit more information on the content and participants etc. of the podcast. 

we're looking to add the following: 

1. A label in the header specifying publication date
2. A label in the header specifying the resource type (podcast)
3. Any information pulling through on participants
4. The ability to add a country of relevance (this is missing for Webinar and Presentation types also)

For a good idea, see the old page set up: 
![fffixture - Google Chrome 20_11_2020 14_46_34_LI](https://user-images.githubusercontent.com/69594823/99813262-5db4dc00-2b3f-11eb-953b-e5aa07068ee9.jpg)

no set request date on these but it would be great to get an idea when you'll have capacity to make these changes.
**Requested Delivery Date:** dd/MMM/YYYY

Tagging: @jamesharle

**Comment by davidebukali** [comment]
@benjamincoleman looks like details from 1 to 4 can be added by the dev team; am not sure about the country, might this need  design input ?

**Comment by benjamincoleman** [comment]
Morning @davidebukali 

Here's my input on each task: 

1. A label in the header specifying publication date
2. A label in the header specifying the resource type (podcast)

Both 1. and 2. are correct, you should have this content for all publication types: 

![Screenshot 2020-12-03 at 10 28 08](https://user-images.githubusercontent.com/64877/100997562-4e2b8f00-3552-11eb-8c1d-5f7fd9aa1268.png)

3. Any information pulling through on participants

I would recommend adding an "about the authors / participants" link to the authors module. This would then scroll the user down, to a new module at the end of the content which can talk either about the authors, or about the participants. I can produce a sketch if you would like to show what I mean. 

4. The ability to add a country of relevance (this is missing for Webinar and Presentation types also)

This is a development task, but yes, there should be a country field for it - otherwise they will not be discovered when a user fitlers resources by a specific country.

**Comment by davidebukali** [comment]
Hi @benjamincoleman thank you for the feedback; Since we both agree on 1 and 2, I have two comments for 3 and 4.

In task 3, there's a card U.I for publications with a list of names for authors; from your description, podcast pages appears to work differently from publications. It would be nice to see a sketch to guide development.

![authors](https://user-images.githubusercontent.com/1607276/101064419-07b35000-35a5-11eb-902f-066abf88c632.png)

For task 4, you are right that adding a country field would allow users to filter podcast pages by a specific country. I could add this field and make sure that it can be searched under resource listings page. Do you think there is design time on this task ?

**Comment by benjamincoleman** [comment]
Morning @davidebukali 

So for the third question - the idea of having an "about the authors/participants" module, I've mocked this up using an example of the live site in which I've edited the code with inspector. 

At the top we have an adapted authors module, which for podcasts has been relabelled "Participants". After their names, we have a link "About the participants" - this links to the fragment ID "about-authors" on the same page. 

<img width="1449" alt="Screenshot 2020-12-04 at 10 11 20" src="https://user-images.githubusercontent.com/64877/101151650-e0e33100-3619-11eb-9ae0-0cc73d73ce65.png">

At the bottom of the page content, we have the new block - an adaptation of the authors module, titled "About the participants" which allows you to tell more about the people involved in the podcast. This would also be able to be used to mention guests authors/participants, and give credits for music etc. 

<img width="1215" alt="Screenshot 2020-12-04 at 10 13 25" src="https://user-images.githubusercontent.com/64877/101151644-dd4faa00-3619-11eb-9526-0076ddd4ca08.png">

This would also be worth running by @AnnaHope & @SimonMurphyDI to check in and see if they have any other requirements that this might help them with.

**Comment by davidebukali** [comment]
@benjamincoleman I think this module works well to split participant details from their names, especially when identifying secondary participants like music owners @jamesharle kindly share your thoughts

**Comment by jamesharle** [comment]
Thanks for this @davidebukali and @benjamincoleman! Sorry for delay coming back.

On the new module, this looks really cool - from my point of view though, I think all that's required is the adapted authors module at the top.

The nature of the AV resource types is such that we will generally be explaining who is participating in the body copy anyway - describing a podcast, for example, is difficult without including who is speaking and why they are speaking to this subject. And if we're doing that in the body copy anyway, the current arrangement - where we can have free text above and below the media anyway - actually gives us more flexibility, because we can credit the participants at the top, and credit the musician after the media item (for example).

So yeah - just the functionality of being able to add participant names in a dedicated module at the top, with a hyperlink to their DI profile for internals or a custom one for externals as we have elsewhere with the author module, would be sufficient. Thanks for suggesting this though Ben, good to think it through!

**Comment by benjamincoleman** [comment]
@davidebukali 

I think in this case then, there's no design task and what needs to happen is that the current author functionality for a resource needs to be made available to a podcast resource. 

<img width="1589" alt="Screenshot 2020-12-14 at 11 33 45" src="https://user-images.githubusercontent.com/64877/102076916-662bca00-3e00-11eb-9153-9c2080e21511.png">

**Comment by davidebukali** [comment]
@sarahharries66 @jamesharle this is ready for testing https://dev.devinit.org/resources/stocktake-global-humanitarian-assistance-during-covid-19-pandemic/
